### PR TITLE
added pg functions keyword and identifier, updated README

### PR DESCRIPTION
**Pull request by fritzy**
Not sure if you want the PG statements set in there, or how you wanted to deal with different dialects, but this is one way to do it. I wanted to be able to enforce some user input filtering on identifiers and keywords.

### CODE REVIEW

**Comment by fritzy** [comment]
@nlf fixed that and replaced function in the examples (were erroneously keyword when they should have been identifier)

**Comment by felixfbecker** [comment]
Thanks for the PR, I don't know how I should feel about it though. The purpose of this module was to take a template string and transform it into an object with placeholder queries and values that both pg and mysql understand, and let them do the escaping. You can use `SQL.raw()` when the input can be trusted or use the database driver escaping functions (that's why I added an example in readme with `mysql.escapeId()`). pg provides something similar: https://github.com/brianc/node-postgres/pull/396 (maybe I should add an example with these too). Adding specific pq functions kind of breaks with the dual-compatibility. I guess it is also generally better to validate stricter - i.e. if you insert a sort direction, check for `asc` or `desc`.
Do you have a specific use case?

**Comment by fritzy** [comment]
Ah, I didn't realize the pg client had these already; these seem to be undocumented features.

I have to say that I don't *like* that it's bothering to produce 2 strings when all I need is one, but otherwise this little module is great.

**Comment by felixfbecker** [comment]
Yeah, I only found them by searching in the repo. Maybe someone should open a PR to add this to their docs?
And what do you think about adding an option to _explicitly_ set the driver?

**Comment by fritzy** [comment]
Yup, that's why I opened issue #3

**Comment by fritzy** [comment]
@felixfbecker I was trying to avoid this:
ORDER BY ${SQL.raw(pg.Client.prototype.escapeIdentifier(args.orderBy))} ${SQL.raw(validSort.has(args.sort.toUpperCase()) ? args.sort : 'DESC')}

**Comment by nlf** [comment]
what if we just allow passing a second parameter to `SQL.raw` that can be an optional escaping function? then it would be more like

```js
let escape = pg.Client.prototype.escapeIdentifier;
let query = SQL`... ORDER BY ${SQL.raw(args.orderBy, escape)}`
```

**Comment by nlf** [comment]
though i'm not sure that's really much better than just doing

```js
let escape = pg.Client.prototype.escapeIdentifier;
let query = SQL`... ORDER BY ${SQL.raw(escape(args.orderBy))}`
```

maybe just a little easier to read since it has fewer parens

**Comment by felixfbecker** [comment]
Yeah, it's unfortunate that the escape functions sits on the client prototype. I would suggest doing
```js
let escape = pg.Client.prototype.escapeIdentifier
```

**Pull request closed without merging**
