### PR TITLE
allow raw values

### PR DESCRIPTION
**Pull request by nlf**
sorry for the extent of this pull request, but this seemed like the best approach.

i also took the liberty of adding some tests. i wasn't sure what testing framework you prefer, if any, so i just used what i was familiar with.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Ok so first of all, thanks for your pr, I think the feature is a great addition!
I created this module initially for my personal use and because it was only 7 lines, I didn't bother with tests. Now that downloads kind of go through the roof, I just added tests and also some notes on the coding style I prefer (I like mocha in BDD flavour with chai with expect flavour and the standard coding style). I also refactored the code to use a for loop, which should make it easier to add features like yours.

If you could implement the feature on top of these changes I will be happy to merge it :)

**Comment by nlf** [comment]
there we go. sorry about the diff, i think my editor did something to the line endings.. viewing the pull request with `?w=1` at the end in the files tab will show what i actually changed.

**Comment by nlf** [comment]
oh, i also added mocha to the devDependencies and a test script to the package.json to make running tests easier for those of us that don't have a global mocha install :)

**Comment by felixfbecker** [comment]
The line endings were my bad, for whatever reason my editor used CRLF. Should be LF of course, fixed it. Allowing `npm test` is definitely a good idea, I added it so it also checks standard coding style (I want to keep this PR clear for the raw values feature). Please check if `npm test` returns no errors.

**Comment by nlf** [comment]
merged in and tests continue to pass :+1:

**Comment by felixfbecker** [comment]
published :)

**Pull request merged**
